version: '2.1'
orbs:
  docker: circleci/docker@2.4.0
jobs:
  test:
    docker:
      - image: cimg/go:1.19
    steps:
      - checkout
      - run: go test -v -short --count=1 $(go list ./...)
  build-and-push:
    executor: docker/machine
    steps:
      - checkout
      - run: echo "$PAT" | docker login --username slehmadi --password-stdin
      - run: docker build -t ghcr.io/slehmadi/karsajobs:latest
      - run: docker push ghcr.io/slehmadi/karsajobs:latest

    
workflows:
  lint-dockerfile:
    jobs:
      - docker/hadolint:
          dockerfiles: Dockerfile
          ignore-rules: DL4005,DL3008
          trusted-registries: docker.io,ghcr.io
  test-app:
    jobs:
      - test
  build-app-karsajobs:
    jobs:
      - build-and-push
          
