# Versi dari CircleCI config
version: '2.1'

# Berisi orbs yang merupakan kumpulan-kumpulan jobs, command, executor, dsb
# Mengambil kumpulan tersebut dari circleci/docker@2.4.0 dengan nama docker
orbs:
  docker: circleci/docker@2.4.0

# Berisi tentang kumpulan jobs
jobs:

# Job 1 bernama test, dengan menggunakan docker yang berbasis image cimg/go:1.19
# Langkah yang dilakukan:
#   - checkout terlebih dahulu
#   - menjalankan perintah untuk mengetes applikasi golang
  lint-dockerfile:
    docker:
      - image: ubuntu-2204:2023.02.1
    steps:
      - checkout
      - run: echo $DOCKER_PASSWORD | docker login --username slehmadi --password-stdin
      - run: docker run --rm --interactive hadolint/hadolint < Dockerfile
# Job 1 bernama test, dengan menggunakan docker yang berbasis image cimg/go:1.19
# Langkah yang dilakukan:
#   - checkout terlebih dahulu
#   - menjalankan perintah untuk mengetes applikasi golang
  test:
    docker:
      - image: cimg/go:1.19
    steps:
      - checkout
      - run: go test -v -short --count=1 $(go list ./...)

# Job 2 bernama build. dengan executor docker/machine yang berasal dari orb docker
# Langkah yang dilakukan:
#   - checkout
#   - Login ke Github Package dengan password PAT berasal dari Environment Variable CircleCI Project
#   - Mem-build docker image
#   - Mem-push docker image ke registry Github Package
  build-and-push:
    docker:
      - image: ubuntu-2204:2023.02.1
    steps:
      - checkout
      - run: echo "$GHCR_IO_PASSWORD" | docker login ghcr.io --username slehmadi --password-stdin
      - run: docker build -t ghcr.io/slehmadi/karsajobs:latest .
      - run: docker push ghcr.io/slehmadi/karsajobs:latest

# Alur kerja dari pipeline
workflows:
  continues-integration:
    jobs:
      - lint-dockerfile


          
